package com.imory.cn.org.dto;

import java.util.Date;

public class OrgAccountInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.id
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.userName
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.openId
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.mobile
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.companyId
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.nickName
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.logoUrl
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orgaccountinfo.createTime
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.id
     *
     * @return the value of orgaccountinfo.id
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.id
     *
     * @param id the value for orgaccountinfo.id
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.userName
     *
     * @return the value of orgaccountinfo.userName
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.userName
     *
     * @param userName the value for orgaccountinfo.userName
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.openId
     *
     * @return the value of orgaccountinfo.openId
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.openId
     *
     * @param openId the value for orgaccountinfo.openId
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.mobile
     *
     * @return the value of orgaccountinfo.mobile
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.mobile
     *
     * @param mobile the value for orgaccountinfo.mobile
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.companyId
     *
     * @return the value of orgaccountinfo.companyId
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.companyId
     *
     * @param companyId the value for orgaccountinfo.companyId
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.nickName
     *
     * @return the value of orgaccountinfo.nickName
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.nickName
     *
     * @param nickName the value for orgaccountinfo.nickName
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.logoUrl
     *
     * @return the value of orgaccountinfo.logoUrl
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.logoUrl
     *
     * @param logoUrl the value for orgaccountinfo.logoUrl
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orgaccountinfo.createTime
     *
     * @return the value of orgaccountinfo.createTime
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orgaccountinfo.createTime
     *
     * @param createTime the value for orgaccountinfo.createTime
     *
     * @mbggenerated Sun Jan 14 15:21:48 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}