package com.imory.cn.inform.dto;

public class UserInformWithBLOBs extends UserInform {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.imgUrl
     *
     * @mbggenerated Sun Dec 24 13:02:39 CST 2017
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.replayContent
     *
     * @mbggenerated Sun Dec 24 13:02:39 CST 2017
     */
    private String replayContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.imgUrl
     *
     * @return the value of user_inform.imgUrl
     *
     * @mbggenerated Sun Dec 24 13:02:39 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.imgUrl
     *
     * @param imgUrl the value for user_inform.imgUrl
     *
     * @mbggenerated Sun Dec 24 13:02:39 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.replayContent
     *
     * @return the value of user_inform.replayContent
     *
     * @mbggenerated Sun Dec 24 13:02:39 CST 2017
     */
    public String getReplayContent() {
        return replayContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.replayContent
     *
     * @param replayContent the value for user_inform.replayContent
     *
     * @mbggenerated Sun Dec 24 13:02:39 CST 2017
     */
    public void setReplayContent(String replayContent) {
        this.replayContent = replayContent == null ? null : replayContent.trim();
    }
}