package com.imory.cn.inform.dto;

import java.util.Date;

public class UserInform {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.id
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.companyId
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    private Integer companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.orgaccoId
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    private Integer orgaccoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.title
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.content
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.mobile
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.state
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.replayContent
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    private String replayContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.replayDate
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    private Date replayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.createTime
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inform.imgUrl
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.id
     *
     * @return the value of user_inform.id
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.id
     *
     * @param id the value for user_inform.id
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.companyId
     *
     * @return the value of user_inform.companyId
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.companyId
     *
     * @param companyId the value for user_inform.companyId
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.orgaccoId
     *
     * @return the value of user_inform.orgaccoId
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public Integer getOrgaccoId() {
        return orgaccoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.orgaccoId
     *
     * @param orgaccoId the value for user_inform.orgaccoId
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public void setOrgaccoId(Integer orgaccoId) {
        this.orgaccoId = orgaccoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.title
     *
     * @return the value of user_inform.title
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.title
     *
     * @param title the value for user_inform.title
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.content
     *
     * @return the value of user_inform.content
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.content
     *
     * @param content the value for user_inform.content
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.mobile
     *
     * @return the value of user_inform.mobile
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.mobile
     *
     * @param mobile the value for user_inform.mobile
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.state
     *
     * @return the value of user_inform.state
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.state
     *
     * @param state the value for user_inform.state
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.replayContent
     *
     * @return the value of user_inform.replayContent
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public String getReplayContent() {
        return replayContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.replayContent
     *
     * @param replayContent the value for user_inform.replayContent
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public void setReplayContent(String replayContent) {
        this.replayContent = replayContent == null ? null : replayContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.replayDate
     *
     * @return the value of user_inform.replayDate
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public Date getReplayDate() {
        return replayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.replayDate
     *
     * @param replayDate the value for user_inform.replayDate
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public void setReplayDate(Date replayDate) {
        this.replayDate = replayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.createTime
     *
     * @return the value of user_inform.createTime
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.createTime
     *
     * @param createTime the value for user_inform.createTime
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inform.imgUrl
     *
     * @return the value of user_inform.imgUrl
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inform.imgUrl
     *
     * @param imgUrl the value for user_inform.imgUrl
     *
     * @mbggenerated Sun Jan 07 16:12:52 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}